load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "part1",
    srcs = ["part1.cc"],
    deps = [
        "@com_google_absl//absl/container:inlined_vector",
        "//util:check",
        "//util:io",
    ],
)
