load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "part1",
    srcs = ["part1.cc"],
    deps = [
        "//util:check",
        "//util:io",
        "@com_google_absl//absl/strings",
    ],
)
